name: Production
env:
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
    AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}
    SCRAPINGWEB: https://datos.gob.ar/dataset/generos-base-datos-linea-144
    INGEST_BUCKET: listas-144
    MODE: GET-LAST
on:
    push: 
        branches: 
            - main
jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment
    environment: production  # Specify the production environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE
  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '*'  # Set the Node.js version
  
      - name: Install pnpm
        run: npm install -g pnpm  # Install pnpm globally
  
      - name: Install Dependencies with pnpm
        run: pnpm install  # Install Node.js dependencies using pnpm
  
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '*'  # Set the Terraform version

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}
          
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
  
      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
  
      - name: Install Serverless Framework with pnpm
        run: pnpm add -g serverless
  
      - name: Deploy with Serverless Framework
        run: serverless deploy